build:
  image: teaci/msys$$arch
  pull: true
  shell: msys$$arch
  commands:
    - svn co https://github.com/Alexpux/MINGW-packages/trunk/mingw-w64-codelite-git
    - cd mingw-w64-codelite-git
    - makepkg-mingw -s --noconfirm --skippgpcheck --noprogressbar

matrix:
  arch:
    - 64
    - 32
